# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Matt Kennedy
description: >- # this means to ignore newlines until "baseurl:"
  Matt is based in Te Whanganui-a-Tara, Aotearoa.
  This website showcases what he's working on and thinking about.
keywords: 
    - education
    - philosophy
    - society
    - environment
    - technology
    - future
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattkennedy.nz" # the base hostname & protocol for your site, e.g. http://example.com
blog_repo: website
# author?_icon: /assets/images/author.jpg
twitter_username: mattkennedy
github_username:  mattkennedynz

# Build settings
markdown: kramdown
# theme: hitchens-theme # commented due to now adding the theme to this repo directly
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
collections:
    pages:
        output: true
        permalink: /:title
    posts:
        output: true
        permalink: /blog/:title

# Styling
feed_icon: /favicon.ico
show_excerpts: true
excerpt_length: 20
hide_search: true
hide_credits: true

# Staticman
# staticman_url: 

# reCaptcha
reCaptcha:
  siteKey: 6LeQr-cUAAAAAHDnILqW3qIoC0QiwSankDwIE8po
  secret: UqP/FoMxPcYCUuLNmU1P/z5F7wZmgxOwhgzKKlHIaLHdDqHQQNZuzR0IfI9V1A7Rvid4NPlO1F/APqbuND1IhYsLf4s4oaMTOBhvKTIU0dL8mdlXCgbtXvVmF5pmokb3NSrdQ4cB6IPE2P6gMNxs5yQwmif5qh9gWoNtZ0OvOiafrFykyms6SkLEkoFvg4Vj71IA4T++YphBMfDn6yh+j0jtO26f8J0N1PwaIY05r44vzlHE7oG5xc8rDWWmN/FyGO7s6Me08CplNqKsHD7i9v2xdkxYOUahmMR/L2MKp9tgF+3v3st9b6fU+Dj0xxj02Hu8PfMr8F2v31OfI7KvW032RpjttdS1tE2vGQqAcN5TPyBiCR4PzGObU3okfSMaZBFWsNhaj6I4nnTWO5szpEY5HoYel6BdE4PiDgPq9rlM3KTqxlRkSd/sClASeRF8+NGKH1phDeQPYh46LJKnX29YvSatcPm+lKoUAz49ZZL0Fj8T7RHam8jQEO5lijw9/mmXb2uTXfYSbFUuUatbfxsDAprjBAQsmPeekwMHN8fdo8hoYKLn9aAlf8m2AnUFNQNznCo6FbY3Z05OqplnNbC1JY3dU3F7iuANQsoDHM1fI2FTKnLlvSfgduqxrSQWvRgRjerL8Q6zCk2Z0+IjDRrutqwTecRAgS9Exj/P87I=

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
